system:
  output: ../outputs
  structure: ../../openmx/soc/POSCAR_rigid
  hamiltonian: ../../openmx/soc/H_symm.npz
  overlap: ../../openmx/soc/S_symm.npz
  orbitals: {Pt: s3p2d2, Se: s3p2d1}
  twist_index: 4
  layers: [1, 1]
  spin: true

bands:
  valley: Gamma
  q_shell: 4
  efermi: -4.5
  num_processes: 61
  blas_threads: 0
  num_bands: 50
  save_hamiltonian: true
  save_wavefunctions: false
  kpath:
    labels: [G, M, K, G]
    points_per_segment: 20
    coordinates:
      G: [0.0, 0.0]
      M: [0.5, 0.0]
      K: [0.3333333333, 0.3333333333]

symmetry:
  valley: Gamma
  q_shell: 4
  efermi: -4.5
  num_processes: 1
  blas_threads: 0
  tolerance: 2.0e-2
  spglib_symprec: 5.0e-2
  representation:
    points:
      G: [0.0, 0.0]
      M: [0.5, 0.0]
      K: [0.3333333333, 0.3333333333]
    degeneracy_tol: 2.0e-3

topology:
  valley: Gamma
  q_shell: 4
  save_wavefunctions: true
  mesh:
    n_b1: 31
    n_b2: 31
    range_b1: [-0.5, 0.5]
    range_b2: [-0.5, 0.5]
  bands:
    vbm1:
      sector: valence
      indices: [-1]
  berry_curvature:
    - bands: vbm1

field:
  zero_potential_layers: [1]
  electric_field_eVpA: 0.0
  inner_symmetric: false
