source_config: ../source/mote2_3.89_K1.yaml
valley: K1
spin: spin_up_projected
symmetry_source: ../../outputs/symm/mote2_3.89_K1
kpath:
  file: ../../../tapw/KPATH.in
  tmat:
  - - 52.4951056667
    - 0.0
    - 0.0
  - - -26.247552834
    - 45.4620950821
    - 0.0
  - - 0.0
    - 0.0
    - 27.0
model:
  n_orb:
  - 1
  - 1
  bM:
    bM1:
    - 0.13820712168748003
    - 0.0
    bM2:
    - 0.06910356084374003
    - 0.11969087836528494
  harmonics:
    intra: 4
    inter: 4
  max_order:
    Kinect: 6
    intra: 4
    inter: 4
fit:
  indices:
  - 0
  coeff_tol: 1.0e-06
bands:
  compare_to_heff: true
  band_slice:
  - 46
  - 54
  plot:
    top_bands: 8
    align: top
    figsize:
    - 3.0
    - 5.8
output:
  dir: ../../outputs/model/mote2_3.89_K1
  verbose: false
  progress: true
