kpath_in: KPATH.in
title: "MoTe2 9.43 K1 TAPW bands"
ymin: -0.9
ymax: 0.9
output: outputs/K1/q03/band/band_comparison.pdf
legend_show: true
legend_loc: upper right
legend_fontsize: 8
global_plot_type: line
marker_size: 1
marker: o
fermi_energy: -4.128442
fermi_line: true

bands:
  - file: outputs/K1/q03/band/energies_vbm.txt
    label: K1 VBM
    color: "#DE6E66"
    linestyle: "-"
    linewidth: 1.2
  - file: outputs/K1/q03/band/energies_cbm.txt
    label: K1 CBM
    color: dodgerblue
    linestyle: "-"
    linewidth: 1.2
