twist:
  bravais: hex
  num_layers: 2
  spin: true
  twist_index_m: 3
  twist_layer: [1, 1]

paths:
  H_file: ../openmx/soc/H.npz
  S_file: ../openmx/soc/S.npz
  input_file: ../openmx/soc/openmx.dat_rigid
  kpath_in: ../KPATH.in
  kpath_out: ../runs/mote2_k_tapw/KPATH.out
  output_dir: ../runs/mote2_k_tapw

compute:
  mode: band
  TAPW: true
  valleys: [1]
  efermi: -4.128442
  n_g: 3
  num_processes: 61
  blas_threads: 0
  num_bands_cal: 20
  eigsh_cal: true
  eig_vec_cal: false
  ge: false
  symmetrize_hamiltonian: false
  hamk_save: false
  orthogonal_basis: false
  zero_potential_layers: [1]
  Electric_field_in_eVpA: 0.0
  Inner_symmetrical_Electric_Field: false
