system:
  name: BiTeI TeTe-AA 5.09
  output: ../outputs/gamma_spinful
  tapw_output: ../../tapw/outputs
  layers: [1, 1]
  spin: all
  orbital_order: Bi-s3p2d2,Te-s3p2d2,I-s3p2d2
  cell:
    - [48.8521468404, 0.0, 0.0]
    - [-24.4260734207, 42.3072001935, 0.0]
    - [0.0, 0.0, 30.0]

project:
  valley: Gamma
  q_shell: 5
  efermi: -4.622009221
  target: valence
  nlow_state_list:
    - [74]
    - [75]
  e_ref: -4.822009221
  workers: 64

symmetry: {}

model:
  target_bands: top
  fit:
    method: linear
    kpoints: [0, 20, 40]
    bands: 14
    one_sided_weight: 0.0
    two_sided_weight: 0.0
  bands:
    compare_to_heff: true
    band_slice: [0, 62]
    plot:
      top_bands: 14
      plot_all_bands: true
      align: top
      figsize: [3.2, 5.8]
  harmonics: {intralayer: 3, interlayer: 3}
  max_order: {kinetic: 12, intralayer: 8, interlayer: 10}
