system:
  name: MgI2
  output: ../outputs/m1_spinful
  tapw_output: ../../tapw/outputs
  layers: [1, 1]
  spin: all
  orbital_order: I-s3p2d2,Mg-s2p2,I-s3p2d2
  cell:
    - [60.9508659523, 0.0, 0.0]
    - [-30.4754329751, 52.7849982976, 0.0]
    - [0.0, 0.0, 50.0]

project:
  valley: M1
  q_shell: 7
  efermi: -4.168612
  target: conduction
  nlow_state_list:
    - [22, 23]
    - [22, 23]
  e_ref: -2.6
  workers: 64

symmetry: {}

model:
  target_bands: bottom
  harmonics: {intralayer: 6, interlayer: 2}
  max_order: {kinetic: 10, intralayer: 4, interlayer: 6}
  fit:
    method: linear
    kpoints: [0, 20, 40, 60]
    bands: 16
    one_sided_weight: 0.0
    two_sided_weight: 0.0
  bands:
    compare_to_heff: true
    band_slice: [0, 16]
    plot:
      bottom_bands: 8
      align: bottom
      figsize: [3.0, 5.0]
      num_bands: 16
