kpath_in: KPATH.in
kpath_out: runs/mgi2_m_gamma_tapw/KPATH.out
title: "MgI2 9.43 M/Gamma TAPW bands"
ymin: -2.2
ymax: 2.2
output: runs/mgi2_m_gamma_tapw/Q_shell_3/band/tapw_mgi2_m_gamma_bands.pdf
legend_show: true
legend_loc: upper right
legend_fontsize: 8
global_plot_type: line
marker_size: 1
marker: o
fermi_energy: -4.093002
fermi_line: true

bands:
  - file: runs/mgi2_m_gamma_tapw/Q_shell_3/band/band_VBM_Gamma_valley.txt
    label: Gamma VBM
    color: "#DE6E66"
    linestyle: "-"
    linewidth: 1.2
  - file: runs/mgi2_m_gamma_tapw/Q_shell_3/band/band_VBM_M1_valley.txt
    label: M1 VBM
    color: dodgerblue
    linestyle: "-"
    linewidth: 1.2
  - file: runs/mgi2_m_gamma_tapw/Q_shell_3/band/band_CBM_M1_valley.txt
    label: M1 CBM
    color: green
    linestyle: "-"
    linewidth: 1.2
