system:
  output: ../outputs_selected_20260929
  structure: ../../openmx/soc/POSCAR_rigid
  hamiltonian: ../../openmx/soc/H_symm.npz
  overlap: ../../openmx/soc/S_symm.npz
  orbitals:
    Mo: s3p2d2
    Te: s3p2d2f1
  twist_index: 6
  layers:
  - 1
  - 2
  spin: true
bands:
  valley: Gamma
  q_shell: 4
  efermi: -4.182383731612424
  num_processes: 5
  blas_threads: 16
  num_bands: 100
  save_hamiltonian: true
  save_wavefunctions: false
  kpath:
    labels:
    - G
    - M
    - K
    - G
    points_per_segment: 20
    coordinates:
      G:
      - 0.0
      - 0.0
      M:
      - 0.5
      - 0.0
      K:
      - 0.3333333333
      - 0.3333333333
symmetry:
  valley: Gamma
  q_shell: 4
  efermi: -4.182383731612424
  num_processes: 5
  blas_threads: 16
  tolerance: 0.02
  spglib_symprec: 0.05
  debug: false
  developer_outputs: true
field:
  zero_potential_layers:
  - 1
  electric_field_eVpA: 0.0
  inner_symmetric: false
