"""Blocks: low-energy subspace and diagonalization utilities."""

from .blocks import (
    align_eigenstates,
    get_H_block,
    project_heff_full,
    ProjectGaugeAnchorCandidate,
    resolve_project_gauge_anchor_candidates,
    resolve_project_gauge_anchors,
    set_projector_blas_threads,
)
from .gamma_layout import (
    GammaCertifiedRawAction,
    GammaClusterClosure,
    GammaEnergyCluster,
    GammaLayoutError,
    GammaRoutedFrames,
    GammaRoutingError,
    GammaRoutingThresholds,
    GammaRowAddress,
    GammaRowLayout,
    assemble_gamma_routed_projectors,
    build_gamma_routed_frames,
    certify_gamma_raw_action,
    certify_routed_covariance,
    close_gamma_projector_clusters,
    cluster_gamma_eigensystem,
)

__all__ = [
    "get_H_block",
    "align_eigenstates",
    # "get_h_dft_low",
    "project_heff_full",
    "ProjectGaugeAnchorCandidate",
    "resolve_project_gauge_anchor_candidates",
    "resolve_project_gauge_anchors",
    "set_projector_blas_threads",
    "GammaCertifiedRawAction",
    "GammaClusterClosure",
    "GammaEnergyCluster",
    "GammaLayoutError",
    "GammaRoutedFrames",
    "GammaRoutingError",
    "GammaRoutingThresholds",
    "GammaRowAddress",
    "GammaRowLayout",
    "assemble_gamma_routed_projectors",
    "build_gamma_routed_frames",
    "certify_gamma_raw_action",
    "certify_routed_covariance",
    "close_gamma_projector_clusters",
    "cluster_gamma_eigensystem",
]
